name: Demo workflow
on: workflow_dispatch
jobs:
  print_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print to console info
        run: echo Hello GH!
      - name: Print fiew lines
        run: |
          echo First line!
          echo Second line!
